export * from './parent/parent.component'
export * from './filter/filter.component'
export * from './footer/footer.component'
export * from './header/header.component'
export * from './thumbnail/thumbnail.component'
export * from './main/main.component'
export * from './wishlist/wishlist.component'
export * from './contact/contact.component'