 export * from '@bc/pipe/price-localiztion.pipe'
 export * from '@bc/directive/price.directive'
 export * from '@bc/directive/thumbnail-sale.directive'
 export * from '@bc/directive/thumbnail-title.directive'
 export * from '@bc/directive/color-circle.directive'
 export * from '@bc/directive/costum-width'